name: my-first-workflow
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Running test command
        run: echo "Hello World this is my first workflow"
      - name: Checking OS release for Githun  hosted runner
        run: cat /etc/os-release
